### ISSUE TITLE
Question: basic auth support?

### ISSUE THREAD

**Issue by bbinet** [tcpcloud/python-aptly#24]
I was concerned about security when using aptly-publisher: does it support some kind of authentication, basic authentication for example?
How do you guarantee security when using aptly-publisher (I guess the aptly API is not publicly available)?

**Comment by fpytloun** [comment]
In most cases, aptly API should be served on private networks. Anyway you can have proxy with authentication (basic, kerberos, whatever, eg. nginx, apache) in front of your API service. Implementing auth in python-aptly (resp. aptly-publisher) is not difficult and I would be happy to see pull request for this feature :-)

**Comment by bbinet** [comment]
Ok, thanks.
I think I will use aptly-publisher on the private network, then serve the generated apt repository publicly through nginx.
