### ISSUE TITLE
Question: Partial mirroring with filter option

### ISSUE THREAD

**Issue by bbinet** [tcpcloud/python-aptly#25]
I was wondering how to configure aptly-publisher so that it will do partial mirror using the  `-filter=` and `-filter-with-deps` option of `aptly mirror create` command?
(See: https://www.aptly.info/doc/aptly/mirror/create/)
Is it already supported?

**Comment by chnyda** [comment]
aptly-publisher is in charge of publishing snapshots of mirrors and repositories. You can create mirrors and repositories with salt-formula-aptly. The `filter` feature is supported by the formula.

**Comment by bbinet** [comment]
Ok thanks, I will have a look to the salt-formula-aptly.
