### ISSUE TITLE
Release with aptly cleanup fixes

### ISSUE THREAD

**Issue by NeroBurner** [tcpcloud/python-aptly#27]
Will there be a release with aptly-cleanup fixes?
commit: https://github.com/tcpcloud/python-aptly/commit/30265a37982d586a1ab4e727efd291ba15849c49

this was merged in February, but the latest release was in January of 2018

**Comment by NeroBurner** [comment]
@fpytloun ping

**Comment by fpytloun** [comment]
Yes, I just released 0.12.12.
